version: "3"
services:
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"

  server:
    build: ./back
    container_name: back-end
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./front
    container_name: front-end
    ports:
      - "3000:80"
    depends_on:
      - server
    stdin_open: true
